version: "3"

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 1s
      timeout: 3s
      retries: 30

  memcached:
    image: memcached:1

  autograph:
    # Autograph is stuck at 2.7.0 because of mozilla-services/autograph#344
    image: mozilla/autograph:2.7.0
    volumes:
      - ${PWD}/autograph/autograph.yaml:/app/autograph.yaml

  selenium:
    image: selenium/standalone-firefox
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4444:4444
    shm_size: 2g

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: kinto:build
    depends_on:
      - db
      - memcached
      - autograph
    environment:
      - KINTO_CACHE_BACKEND=kinto.core.cache.memcached
      - KINTO_CACHE_HOSTS=memcached:11211 memcached:11212
      - KINTO_STORAGE_URL=postgresql://postgres@db/postgres
      - KINTO_PERMISSION_URL=postgresql://postgres@db/postgres
      - KINTO_SIGNER_AUTOGRAPH_SERVER_URL=http://autograph:8000
    ports:
      - 8888:8888
    volumes:
      - $PWD:/app
    command: uwsgistart

  tests:
    build:
      context: .
      dockerfile: Testing.Dockerfile
    image: kinto:tests
    depends_on:
      - web
      - selenium
    environment:
      - SERVER=http://web:8888/v1
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
    volumes:
      - $PWD/tests:/app
      - $PWD/mail:/app/mail/
      - $PWD/kinto-remote-settings:/app/kinto-remote-settings
      - $PWD/setup.cfg:/app/setup.cfg
    command: start
