# These environment variables must be set in CircleCI UI
#
# DOCKERHUB_REPO - docker hub repo, format: <username>/<repo>
# DOCKER_USER
# DOCKER_PASS
#
version: 2
jobs:
  build_test_publish:
    machine:
      docker_layer_caching: true

    working_directory: ~/kinto-dist

    steps:
      - run:
          name: Install essential packages
          command: |
            sudo apt-get update
            sudo apt-get install -y ca-certificates curl git openssh-client

      - checkout

      - run:
          name: Create version.json
          command: |
            # create a version.json per https://github.com/mozilla-services/Dockerflow/blob/main/docs/version_object.md
            printf '{"commit":"%s","version":"%s","source":"https://github.com/%s/%s","build":"%s"}\n' \
            "$CIRCLE_SHA1" \
            "$CIRCLE_TAG" \
            "$CIRCLE_PROJECT_USERNAME" \
            "$CIRCLE_PROJECT_REPONAME" \
            "$CIRCLE_BUILD_URL" > version.json

      - run:
          name: Build
          command: docker-compose build

      - run:
          name: Start once
          command: |
            # This will start all the dependencies first
            docker-compose run web sleep 10

      - run:
          name: Migrate
          command: |
            mkdir mail
            sudo chmod 777 mail
            docker-compose run web migrate

      - run:
          name: Env
          command: docker-compose run megaphone env

      - run:
          name: Wait for megaphone
          command: |
            # Megaphone can take an arbitrary amount of time to start
            # up (probably waiting for mysql to accept connections)
            wget -q --tries=30 --retry-connrefused --waitretry=1 -O /dev/null "http://localhost:5555/__heartbeat__"
            docker logs megaphone

      - run:
          name: Tests
          command: |
              docker-compose run tests start

      - run:
          name: Push to Dockerhub
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              ./bin/deploy-dockerhub.sh latest
            fi
            if [ -n "${CIRCLE_TAG}" ]; then
              ./bin/deploy-dockerhub.sh "$CIRCLE_TAG"
            fi
  integration_test:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/kinto-dist
    steps:
      - checkout
      - run:
          name: "Set Python Version"
          command: |
            pyenv global 3.7.0
      - run:
          name: Install Docker Compose
          command: |
            set -x
            sudo bash -c "curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose"
            sudo chmod +x /usr/local/bin/docker-compose
      - run:
          name: Set hosts
          command: |
            echo 127.0.0.1 localhost | sudo tee -a /etc/hosts
            cat /etc/hosts
      - run:
          name: Build
          command: docker-compose build

      - run:
          name: Start once
          command: |
            # This will start all the dependencies first
            docker-compose run web sleep 10

      - run:
          name: Setup env and run tests
          command: |
            mkdir mail
            sudo chmod 777 mail
            docker run -d --shm-size 2g --net host selenium/standalone-firefox
            docker-compose run web migrate
            docker-compose up -d web
            pip install pytest-selenium
            pytest --driver Remote --capability browserName firefox --base-url=http://localhost:8888/v1/admin --verify-base-url --html=integration-test.html --self-contained-html tests/test_integration.py
      - store_artifacts:
          path: integration-test.html

workflows:
  version: 2
  main:
    jobs:
      - build_test_publish:
          filters:
            tags:
              only: /.*/
      - integration_test
